<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2d80828e-fce3-4325-ab03-abe1ef536201</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TobaccoEntities\**" />
    <Compile Remove="Views\**" />
    <Content Remove="TobaccoEntities\**" />
    <Content Remove="Views\**" />
    <EmbeddedResource Remove="TobaccoEntities\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="TobaccoEntities\**" />
    <None Remove="Views\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Models\Jobs\CleartStallDetectionJob.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Models\Jobs\NewFile.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.10.0.20240616" />
    <PackageReference Include="Quartz" Version="3.8.1" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.8.1" />
    <PackageReference Include="Quartz.Jobs" Version="3.8.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Archives\" />
    <Folder Include="Images\" />
    <Folder Include="Images\04.10.2024\TooManyPeopleAtStallDefect\" />
    <Folder Include="Archives\" />
    <Folder Include="Migrations\" />
    <Folder Include="Temp\" />
    <Folder Include="Videos\" />
    <Folder Include="Playlists\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TobaccoEntities">
      <HintPath>..\..\TobaccoEntities\TobaccoEntities\bin\Debug\net8.0\TobaccoEntities.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="ffmpeg.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Start.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
